### ISSUE TITLE
Fails to load on HA 2024.12 beta 3

### ISSUE THREAD

**Issue by sparkydave1981** [sudoxnym/saas#4]
Got this error in the log after updating from HA version 2024.12.b2 to b3.
```
Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:366
integration: Sensor (documentation, issues)
First occurred: 17:13:27 (1 occurrences)
Last logged: 17:13:27

Error while setting up sleep_as_android platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 366, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/sleep_as_android/sensor.py", line 50, in async_setup_entry
    await instance.subscribe_root_topic(async_add_entities)
  File "/config/custom_components/sleep_as_android/__init__.py", line 292, in subscribe_root_topic
    self._subscription_state = await subscribe_2022_03(
                               ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "/config/custom_components/sleep_as_android/__init__.py", line 262, in subscribe_2022_03
    result = subscription.async_prepare_subscribe_topics(
        hass=_hass,
        new_state=_state,
        topics=_topic,
    )
TypeError: async_prepare_subscribe_topics() got an unexpected keyword argument 'new_state'. Did you mean 'sub_state'?
```

**Comment by sparkydave1981** [comment]
Sorry, wrong integration
